type User @table {
  displayName: String!
  email: String!
  role: String!
  photoUrl: String
}

type Screen @table {
  name: String!
  location: String!
  description: String
  lastHeartbeat: Timestamp
}

type MenuItem @table {
  name: String!
  price: Float!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  allergens: [String]
  dietaryInfo: [String]
  imageURL: String
}

type Menu @table {
  creator: User
  name: String!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type Announcement @table {
  creator: User
  title: String!
  content: String!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  imageURL: String
  priority: String
}

type ScreenContent @table {
  screen: Screen!
  menu: Menu
  announcement: Announcement
  contentType: String!
  displayOrder: Int!
  startDate: Date!
  endDate: Date!
}